article/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard, name = "dashboard" ),
    path('addarticle/',views.addArticle, name = "addarticle" ),
    path('news/',views.Addnews, name = "news" ),
    path('article/<int:id>',views.detail, name = "detail" ),
    path('update/<int:id>',views.updateArticle, name = "update" ),
    path('delete/<int:id>', views.deleteArticle, name = "delete" ),
    path('', views.articles, name = "articles" ),
    path('comment/<int:id>', views.addComment, name = "comment" ),
    
    

]

aıcblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register, name = "register" ),  
    path('login/',views.loginUser, name = "login" ), 
    path('logout/',views.logoutUser, name = "logout" ), 
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank = True,null = True,verbose_name = "Add Image")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']



class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name="Article",related_name="comments")
    comment_author = models.CharField(max_length = 50, verbose_name="Name")
    comment_content = models.CharField(max_length=200, verbose_name="Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    
    
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title" , "content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from  .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required


# Create your views here.
def articles(request):
    articles = Article.objects.all()
    return render(request,"articles.html", {"articles" : articles})

def index(request):
    return render(request,"index.html")

def Addnews(request):
    return render(request,"news.html")
  
def about(request):
    return render(request,"about.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }

    return render(request, "dashboard.html", context)

@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit = False)
        
        article.author = request.user
        article.save()


        messages.success(request, "Article was created succesfully...")
        return redirect("article:dashboard")

    return render(request, "addarticle.html", {"form" : form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    
    comments = article.comments.all()
    return render(request, "detail.html", {"article" : article,"comments":comments})

@login_required(login_url="user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article )
    
    if form.is_valid():
        article = form.save(commit = False)
        
        article.author = request.user
        article.save()

        messages.success(request, "Article was updated succesfully...")
        return redirect("article:dashboard")


    return render(request, "update.html",{"form" : form})
    
@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)

    article.delete()

    messages.success(request,"The Article was deleted successfully")
    
    return redirect("article:dashboard")

@login_required(login_url="user:login")
def addComment(request,id):
    article= get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content=comment_content)
        
        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}


{% block body %}




<div class="jumbotron text-center">
   <h3> ABOUT AIC </h3>
   <p>
   AIC is a platform which includes articles about aviation. If you want to share your information, Register and Write...
   <br>
   Aviation,Innovation,Consultation</p>

</div>

{% endblock %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Create an Article</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form|crispy }}
    <br>
    <button type = "submit" class = "btn btn-danger">Create an Article</button>
    </form>
  
  </div>
</div>


 



{% endblock %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<h3>Articles</h3>
<hr>



{% if articles %}



{% for article in articles %}
<div class="row">

      <!-- Post Content Column -->
    <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}"><h3 class="mt-4">{{article.title}}</h3></a>

        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}} 
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        
        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">
            {{article.content|safe|truncatewords:40}}
        
        </p>

        <a style ="float : right" href="{% url 'article:detail' article.id %}" class = "btn btn-danger">Read More</a>

        <hr>


        
    
    </div>
</div>





{% endfor %}

    
{% else %}

<div class = "alert alert-danger">
    There is no article!
</div>

{% endif %}

{% endblock %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Control Panel</h3>
<hr>

<p>
    Welcome, <small>{{ request.user.username}}</small>
<p>
<hr>

<a class = "btn btn-danger" href = "/articles/addarticle">Add Article</a>
<hr>

{% if articles %}

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  
  {% for article in articles %}
    
 <tr>
    <th scope="row">{{article.id}}</th>
    <td><a href = "{% url 'article:detail' article.id %}">{{article.title}}</a></td>
    <td>{{article.author.username}}</td>
    <td>{{article.created_date}}</td>
    <td><a href= "{% url 'article:update' article.id %}" class = "btn btn-danger">Update</a></td>
    <td><a href= "{% url 'article:delete' article.id %}" class = "btn btn-danger">Delete</a></td>
 </tr>
    {% endfor %}



    <!-- <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>-->
    
  </tbody>
</table>
 

{% else %}

<div class = "alert alert-danger">
    You have not created any article yet...
</div>

{% endif %}





{% endblock %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}} 
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        
        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">
            {{article.content|safe}}
        
        </p>

        <hr>

        <h4>Comments</h4>
        <hr>
        {% if comments %}
        {% for comment in comments %}

          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.comment_author}}</h5>
              {{comment.comment_date}}
              <br>
              {{comment.comment_content}}
            </div>
          </div>


        {% endfor %}

        

        {% else %}
        <div class ="alert alert-danger">
          There is no comment for this article
        </div>
      

        {% endif %}

     <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form method = "post" action="{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="formGroupExampleInput">Your Name</label>
                  <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Please write your name...">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput">Comment</label>
                <textarea name= "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Submit</button>
            </form>
          </div>
        </div>   

        

        

    </div>
             

</div>



{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block body %}


<div class="col-md-6 offset-md-0">
   <a class="navbar-brand" href="#">
      <img src="/media/kapak1.png" width="1100" height="500" alt="">
   </a>
</div>




{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>AIC Blog</title>
</head>
<body>
        {% include "includes/navbar.html" %}
        
        <div style = "margin-top : 100px; margin-bottom:100px;" class=" container ">
        {% if messages %}
            
                {% for message in messages %}
                <div{% if message.tags %} class="aler alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                
                {% endfor %}
         
        {% endif %}
            {% block body %}
            
            {% endblock %}


        </div>






        <script src="{% static 'js/bootstrap.min.js' %}"></script> 
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

    </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Login</h3>
    <hr>
    <form method = "post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type = "submit" class = "btn btn-danger">Login</button>
    </form>
    <a href="{% url 'user:register'  %}"><h5 class="mt-4">Haven't you registered yet?</h5></a>
    <hr>
  </div>
</div>





{% endblock %}

templates/news.html
<div>Coming Soon...</div>

templates/register.html
{% extends "layout.html" %}


{% block body %}


{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Register</h3>
    <hr>
    <form method = "post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type = "submit" class = "btn btn-danger">Register</button>
    </form>
  
  </div>
</div>



{% endblock %}

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
  <h3>Update the Article</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form|crispy }}
    <br>
    <button type = "submit" class = "btn btn-danger">Update the Article</button>
    </form>
  
  </div>
</div>


 



{% endblock %}